### PR TITLE
[wip] erc20 escrow

### PR DESCRIPTION
**Pull request by joaoh9**

### CODE REVIEW

**Review by amaredeus — CHANGES_REQUESTED** [review]
One small change that I think would really help the team test this. If you can create a README.MD file under packages/truffle/docs/README.md

And in that filer post the contracts hash along with which testnet is deployed to. The hash can be replaced with every deployment/change to keep things simple

**Comment by amaredeus** [comment]
Looks like the DAO has an additional level 3 and 4, which is generally whales

https://www.notion.so/bankless/FAQs-29353e63e864411aabc0061d04906c16#86fd59bcbe2b459a82a89196eec88d5d

Might be a good idea to include it under Levels enum

```
  enum Levels {
    GUEST_PASS,
    LEVEL_0,
    LEVEL_1,
    LEVEL_2,
    LEVEL_3,
    LEVEL_4
  }
  ```

**Comment by amaredeus** [comment]
I see that there is an emergency withdrawal set to `onlyPayer(bountyHash)`. Can we set this to be a multisig wallet instead? I think this merits discussion on having a multisig "admin" of sorts that can cancel/reverse the bounty

**Comment by jordaniza** [comment]
I'm going to close this for now, as no activity for a while.

**Pull request closed without merging**
