### PR TITLE
added sorting keys support for Bounty Status and Paid Status

### PR DESCRIPTION
**Pull request by thedarkrai07**

### CODE REVIEW

**Review by tescher — CHANGES_REQUESTED** [review]
Tests are failing around the sorting and pagination changes. I think you need to fix/adjust/add tests based on your changes. To run tests:

yarn test:unit
yarn test:integration
yarn test:coverage

Also, the Paid/Unpaid filter doesn't seem to work all the time. Not sure if your changes caused that, or if it an existing issue 
image

**Comment by thedarkrai07** [comment]
I have fixed the test cases. I am checking into `Paid` logic

**Review by tescher — CHANGES_REQUESTED** [review]
A couple things I found:
1) When first running, I was getting "aggregateFn is not a function" errors. I did a rebuild and that fixed it. Probably not an issue because I'm guessing the deploy does a rebuild
2) Initial load is not sorting correctly. Here you'll notice it should be sorting on Reward descending, but I think it is actually sorting on created date:
image

**Comment by thedarkrai07** [comment]
I see that this issue exists in the current version as well. Let me see

**Review by tescher — APPROVED** [review]
Looks good!

**Review by Behold3th — APPROVED** [review]

**Pull request merged**
