### PR TITLE
Feature/fix netlify deployment

### PR DESCRIPTION
**Pull request by amaredeus**

### CODE REVIEW

**Comment by Oktalize** [comment]
@amaredeus hey this is just a logistics thing, but it looks like this PR includes unmerged code from this PR - https://github.com/BanklessDAO/bounty-board/pull/41

Maybe merge that PR first?

Everything else should be good besides that I think.

**Comment by amaredeus** [comment]
@Oktalize Oops yeah I may have pulled in those changes thinking that it would get merged first. 

If the other PR looks good to you then I'll go ahead and get that merged first

**Comment by amaredeus** [comment]
Will merge once this PR #41 is merged

**Comment by Oktalize** [comment]
> If the other PR looks good to you then I'll go ahead and get that merged first

Looks like paul approved the other one so you should be good there.

**Review by Behold3th — APPROVED** [review]

**Comment by amaredeus** [comment]
Closing this because #50 is created with only netlify fix changes

**Pull request closed without merging**
